### ISSUE TITLE
The background is messed up on the login screen

### ISSUE THREAD

**Issue by kitsune7** [cs340tabyu/cs340summer2018#18]
![screen shot 2018-08-02 at 11 46 36 am](https://user-images.githubusercontent.com/1205871/43601135-c7ba720a-9649-11e8-9d05-e5a6f8f63f9f.png)

**Comment by frigid-dev** [comment]
This one is a strange issue as it only happened during testing. None of us have ever seen it when running on a variety of emulators and configurations.

**Comment by frigid-dev** [comment]
Closed as unrepoducible.
