### ISSUE TITLE
Game crashed puts game out of sync

### ISSUE THREAD

**Issue by astind** [cs340tabyu/cs340summer2018#22]
After my game crashed I logged back into the game. Once I was logged in it said it was my turn on everyone screen but on my screen it says that it is still the turn before mine. I cannot draw any cards because it says it is not my turn, and the person before me cannot do anything either.

Basically if a person crashes the game is broken. It made everything out of sync, and then peoples cards changed. Also routes began to disappear

**Comment by dustintwatkins** [comment]
We made the deck shuffle upon being exhausted. The game now doesn't crash if the deck is empty.
