### ISSUE TITLE
No one can play

### ISSUE THREAD

**Issue by ezrajc** [cs340tabyu/cs340summer2018#27]
All players game tells them its not their turn

**Comment by dustintwatkins** [comment]
do you guys need us to reboot the server?

**Comment by kitsune7** [comment]
I think as we've been doing bug fixes, we might have fixed this because we haven't been able to reproduce this.

**Comment by kitsune7** [comment]
There is an issue with turns under certain circumstances at the beginning of the game that can be reproduced.

**Comment by dustintwatkins** [comment]
This has now been solved. The player whose turn it should be at the beginning of the game now always has their turn first. This was solved by refactoring the state logic and the game presenter constructor.
