### ISSUE TITLE
Claiming double routes

### ISSUE THREAD

**Issue by jtcooper** [cs340tabyu/cs340summer2018#34]
Trying to claim double routes in general is weird, especially when someone else has claimed one of them. Sometimes if you try, it'll let you claim one but erase the one already there. When that happens, it only shows for your client, it doesn't update your points, it takes your train cards, and your turn doesn't end. This was a 4 player game.

It also lets you claim both routes in a double.

**Comment by dvwilliamson** [comment]
These are from the same game, different tablets

![screenshot_1533231553](https://user-images.githubusercontent.com/6345638/43604208-70d4e0b6-9652-11e8-9983-87afeed97eed.png)
<img width="272" alt="screen shot 2018-08-02 at 12 51 14 pm" src="https://user-images.githubusercontent.com/6345638/43604358-ca13cfe8-9652-11e8-858f-c1d619f6cf2d.png">
