### ISSUE TITLE
Incorrect IP doesn't notify you

### ISSUE THREAD

**Issue by gaskint** [cs340tabyu/cs340summer2018#35]
If the IP is wrong, you don't get a toast or anything, it just kicks you back from register to login mode with no explanation of why.

**Comment by dvwilliamson** [comment]
I cannot reproduce this error, when my server settings are incorrect, my screen shows the following. Can anyone else reproduce it?

![screen shot 2018-08-02 at 8 51 45 pm](https://user-images.githubusercontent.com/6345638/43621678-f1f48532-9695-11e8-825b-c86aa5cb602a.png)

**Comment by dvwilliamson** [comment]
Added loading screen so that while it is trying to connect to the server, you can tell a little better that it is communicating with the server and then the toast makes more sense when it comes.
