### ISSUE TITLE
Stolen Wilds

### ISSUE THREAD

**Issue by gaskint** [cs340tabyu/cs340summer2018#45]
Sometimes, when you claim a route with a specific color AND some wilds, the game ends up taking more wilds away from the player than it is supposed to.

For example:

1) Tried claiming a blue route of length 4
2) I had 3 blues and 2 wilds in my hand
3) Tried to claim the route with 3 blues and 1 wild
4) Game took all 3 blues and 2 wilds
5) I was mad I lost a wild!

This isn't 100% reproducible, though, but we did see it at least twice.

**Comment by gaskint** [comment]
Here is another, more reproducible instance. We were able to do this consistently:

1) In hand: 4 wilds and 2 yellows
2) Tried to claim a yellow route of length 3 with 2 yellows and 1 wild
3) It took 2 yellows and 3 wilds, leaving the player with just one wild.

**Comment by pjohnst5** [comment]
Fixed. Added "return" to line 120 of Player.java
