### ISSUE TITLE
Can't join a different game after logging in as a different user

### ISSUE THREAD

**Issue by kitsune7** [cs340tabyu/cs340summer2018#5]
I created a game, 'Foxes', as user 'happikitsune' and then logged out. I then logged in as user 'kitsune' and I couldn't join a game another player started, 'Foxes2'. I get the errors (it alternates evertime I press 'join game'): "Invalid game id". or "Error joining game. Already in a game."

**Comment by frigid-dev** [comment]
As there is no logout button this must have been done using the back button. There is no requirement to implement a logout feature so I have fixed this by preventing the default behavior of the back button. It now behaves as a back to OS button the same way using it on the login screen would.
