### ISSUE TITLE
Showing wrong number of cards

### ISSUE THREAD

**Issue by jtcooper** [cs340tabyu/cs340summer2018#53]
info view shows number of cards drawn, not in hand

**Comment by tylermercer** [comment]
Can you elaborate?

**Comment by jtcooper** [comment]
Yeah, we noticed when we opened the info dialog view, the number of train cards it says each player has in their hands doesn't match the number they actually have. I think the number showing in that view is based on the total number of train cards they've drawn.

**Comment by tylermercer** [comment]
Oh I see, so the amount isn't being decremented when cards are spent to claim routes?
