### ISSUE TITLE
End of game issues

### ISSUE THREAD

**Issue by jtcooper** [cs340tabyu/cs340summer2018#61]
1. Game doesn't end when train cars drops below 2
2. Can go negative in train cars
3. count in the destination card deck is off by 1

**Comment by tylermercer** [comment]
@jtcooper Regarding number 3: How could you tell the destination card deck was off? Presumably this was before the game over screen appeared? When did you notice it? How do you know it's connected to the end of game? Thanks

**Comment by dsegrera** [comment]
Issue 1 is fixed
