### ISSUE TITLE
Game List does not refresh

### ISSUE THREAD

**Issue by dsegrera** [cs340tabyu/cs340summer2018#70]
This is a problem that only happens when the server is running on a different computer than the client when the client is connected to the BYU Ethernet. I was the first to join a specific game. After joining a game, I can’t see other players who have joined: it still says 1/2 players, even though someone has already joined.

**Comment by gaskint** [comment]
We weren't able to replicate this. Once a game that you are in has started the next action your client takes is to join you to the game, and if it is not a game that your in then list updated correctly.
